# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20171101_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_last_updated',
            field=models.DateField(default=datetime.datetime(2017, 11, 1, 17, 32, 52, 936845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2017, 11, 1, 17, 32, 52, 936819, tzinfo=utc)),
        ),
    ]
