# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 13:21
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0009_auto_20171126_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook.Category')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='region',
            field=models.CharField(choices=[('af', 'African'), ('ea', 'East Asian'), ('eeu', 'Eastern European'), ('la', 'Latin American'), ('mde', 'Middle Eastern'), ('na', 'North American')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 13, 20, 57, 185220, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 13, 20, 57, 185199, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='couple',
            name='date_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 13, 20, 57, 181800, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='couple',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 13, 20, 57, 181776, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inrecipe',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inrecipe',
            name='unit',
            field=models.CharField(choices=[('ml', 'Mililiters'), ('g', 'Grams'), ('l', 'Liters'), ('kg', 'Kilograms'), ('cp', 'Cup'), ('pc', 'Piece'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 13, 20, 57, 183051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 13, 20, 57, 183028, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cookbook.Category'),
        ),
    ]
