# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0010_auto_20171130_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 13, 22, 44, 261648, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 13, 22, 44, 261628, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='couple',
            name='date_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 13, 22, 44, 258080, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='couple',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 13, 22, 44, 258056, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 13, 22, 44, 259272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 13, 22, 44, 259252, tzinfo=utc)),
        ),
    ]
