# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 15:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0011_auto_20171130_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 15, 20, 35, 728338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 15, 20, 35, 728318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='couple',
            name='date_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 15, 20, 35, 724858, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='couple',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 15, 20, 35, 724833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inrecipe',
            name='unit',
            field=models.CharField(choices=[('ml', 'Milliliters'), ('g', 'Grams'), ('l', 'Liters'), ('kg', 'Kilograms'), ('cp', 'Cups'), ('pc', 'Pieces'), ('tsp', 'Teaspoons'), ('tbsp', 'Tablespoons')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 15, 20, 35, 726069, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 15, 20, 35, 726046, tzinfo=utc)),
        ),
    ]
